### ISSUE TITLE
Signature not matching

### ISSUE THREAD

**Issue by shashankkumar88** [Mastercard/oauth1-signer-csharp#12]
API - Standard Currency Conversion Calculator - Get Settlement Currencies

Generated with the C# library-
OAuth 
oauth_consumer_key="sfjCLAr0YrkZrURUaMjFL711iNV-Ip8Yw-ufTayE7f7dc766%2194dc33ebddba4d99bb797c3fb94aae2a0000000000000000",
oauth_nonce="40e031a22c0bbcde",
oauth_timestamp="1616572266",
oauth_signature_method="RSA-SHA256",
oauth_version="1.0",
oauth_body_hash="47DEQpj8HBSa%2B%2FTImW%2B5JCeuQeRkm5NMpJWZG3hSuFU%3D",
oauth_signature="ec%2BHYby9l0%2BkYjvQyxIrNCO6UayxaB%2FnxRG4CTd%2FLLhwJx4gzk6WCvA2EAgxHHxRRm1hevfoWgq5khRoltUl9F6%2BOGzdrCEThs0%2BKpgWnjE3GjUydIMO0X2bAVxA22ljvgTZbv4Im7ffPVn2vepKL5JjFkSMTiLpWsrTYpuw3ZUWOFa6%2ByNDhFIGlZdSk5ZPNPIl3PJ6EARuhIQskCjMMh0CDljv4VwnNWRCEwQt1JP%2FFKYQSLqEL%2FD7wuF2sSCghv0xDnoq1BWzClDm5jDOuitzhckk15%2B8YXK8JiR9dw1t7LAkXvJu%2BME1aS%2BMJm3QKqG%2BEYIiyZN8986HslThRw%3D%3D"

POSTMAN Response-
{
    "Errors": {
        "Error": [
            {
                "Source": "Gateway",
                "ReasonCode": "AUTHENTICATION_FAILED",
                "Description": "OAuth signatures did not match. Acceptable signature base string: GET&https%3A%2F%2Fsandbox.api.mastercard.com%2Fsettlement%2Fcurrencyrate%2Fconversion-rate-issued&date%3D2020-09-01%26oauth_body_hash%3D47DEQpj8HBSa%252B%252FTImW%252B5JCeuQeRkm5NMpJWZG3hSuFU%253D%26oauth_consumer_key%3DsfjCLAr0YrkZrURUaMjFL711iNV-Ip8Yw-ufTayE7f7dc766%252194dc33ebddba4d99bb797c3fb94aae2a0000000000000000%26oauth_nonce%3D40e031a22c0bbcde%26oauth_signature_method%3DRSA-SHA256%26oauth_timestamp%3D1616572266%26oauth_version%3D1.0",
                "Recoverable": false,
                "Details": null
            }
        ]
    }
}

Points noted:
1. HTTP method and url is included in POSTMAN returned signature
2. Double quotes. comma and = are encoded in POSTMAN returned signature
3. There are some other encoding differences in the POSTMAN returned signature

**Comment by danny-gallagher** [comment]
@shashankkumar88 We will require more information before looking any deeper into your issue.
Can you address the following points for us?

1. Is there a particular reason you are generating the OAuth signature programatically (using this OAuth library), and then using Postman to send the request? We would suggest both signing and sending your requests in code. This should resolve the issue you're seeing above.
2. If you wish to make calls using a Rest client, we would suggest that you make use of our [insomnia plugin](https://github.com/Mastercard/insomnia-plugin-mastercard-auth), this will handle all of the OAuth signing for you.
3. If it's absolutely necessary for you to call the service as you've outlined above, please provide us with the following:
  - The version of the c-sharp signing library you're using
  - The code you've implemented to both build the request, and generate the OAuth signature
  - A screenshot of your Postman setup, including all of the parameters, properties and headers that you're sending to the service

**Comment by shashankkumar88** [comment]
Managed to fix it. Thanks for your support.
