### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by mopedisanocrb** [Mastercard/oauth1-signer-csharp#24]
HI all.
We are working with Mastercard Send API's.
We used client for API's generated by openapi and using restsharp as client version ~106.12 Mastercard.Developer.OAuth1Signer.RestSharpV2 v1.3.3.

Recently we decided to update the packages of restsharp to latest version 112 and also Mastercard.Developer.OAuth1Signer.RestSharpV2 to 1.5.1

After updating we start getting 400 reponses with following error: 
Error calling CreatePayment: {"Errors":{"Error":[{"Source":"Gateway","ReasonCode":"**INVALID_BODY_HASH**","Description":"Bad Request - The provided oauth_body_hash does not match the RSA-SHA256 hash of the request payload. Calculated: x++p2PknXBdrs+9Y4PC****FtHSgqqPgPjD/YxGvfaU=, Received: LpxcaG4bfd**%2B**I****ECDPUvqYE73oG%2BH8PnNQ1mudc2M**%3D**","Recoverable":false,"Details":null}]}}

I also created new solution with openapi cli generator as described in you project readme file and yet get same response.
Could you please check maybe it related to changes betwen v1.3.3 to 1.5.1?
thanks in advance

**Comment by NehaSony** [comment]
HI @mopedisanocrb 
Between v1.3.3 to 1.5.1 we have only upgraded versions of our dependencies and security upgrades. There have been no changes to the existing implementation. I recommend that you to go through https://developer.mastercard.com/platform/documentation/security-and-authentication/gateway-error-codes/
Do verify that your payload is not empty as your calculated body_hash count does not match the generated one.

**Comment by karen-avetisyan-mc** [comment]
Please reopen the issue, if there are still questions. Closing it for now.
