### ISSUE TITLE
ClientID not provisioned. Is this a PEBKAC or Mastercard issue?

### ISSUE THREAD

**Issue by andyvans** [Mastercard/oauth1-signer-csharp#8]
Hi again. I am receiving this error when registering a sample card number using RegisterCardUsingPOSTWithHttpInfo against https://sandbox.api.mastercard.com/issuer/spendcontrols/v1/card

`{"code":"-32603","errors":[{"source":"Validation","reasonCode":"clientid.invalid","description":"ClientID not provisioned.","recoverable":false}],"message":"Internal Error"}`

I created a sandbox project last week and am using the consumer key and client cert from that project.

Is this because the Sandbox is not set up correctly, or do I have the authorisation header set incorrectly?

**Comment by TutteRamson** [comment]
If the error has anything to do with the request signature, you will get one of the errors listed here:
https://developer.mastercard.com/platform/documentation/security-and-authentication/gateway-error-codes/

As this particular error suggests, your client id requires provisioning in the backend system.
Please reach out to the support team as per the options listed here: https://developer.mastercard.com/support/

**Comment by andyvans** [comment]
Thanks for your help. I have raised a ticket.
